### PR TITLE
Adding DB support to the whole app

### PR DESCRIPTION
**Pull request by mickeydarrenlau**
Adding db support and the appropriate schema and the api endpoint.
Currently read only.

### CODE REVIEW

**Comment by safeboot** [comment]
LGTM!

I'll review it and tweak it if necessary.

**Comment by safeboot** [comment]
A few comments here, can you explain why you re-added the `example-config.json` file? We've moved to SQLite so I don't think we have a use for JSON files.

Also I see you installed `compression` and `sirv` but haven't used them, is there something you're planning to do with them or are they leftovers?

The other changes look good to me, again I have to test them but I am currently travelling.

-Safeboot

**Comment by mickeydarrenlau** [comment]
Oh no
Just forgot to remove them

Also the two lib is the code from yours

**Comment by mickeydarrenlau** [comment]
I can still help you with the code but might need a little more effort to do.

I moved to turso and it's the exact same code except the way the query works

So mine is
```js
app.use('/api/settings', async (req, res) => {
  const stmt = await db.execute('SELECT * FROM settings');
  let data = []
  for(let each of stmt["rows"]) {
    data.push({"name":  each[0], "value": each[1]})
  }
  res.json(data);
});
```

Don't worry 
I will still be able to contribute but due to needing to rewrite every piece of the api handler before push might be a bit of work but ok.

**Comment by mickeydarrenlau** [comment]
Also another update
Motion won't work with SSR
https://github.com/vueuse/motion/issues/58

**Comment by mickeydarrenlau** [comment]
Do I push my changes

cause I have fixes for the animation and turso lib support all local sqlite and libsql servers

**Comment by safeboot** [comment]
Closing as the database implementation has been completed. Please take a look and test it yourself. Obviously we will need changes but this is a good starting point.

**Pull request closed without merging**
